export const reducerCases = {
  TOGGLE_LOGIN_MODULE: "TOGGLE_LOGIN_MODULE",
  TOGGLE_SIGNUP_MODULE:"TOGGLE_SIGNUP_MODULE",
  CLOSE_AUTH_MODULE:"CLOSE_AUTH_MODULE",
  SET_USER : "SET_USER",
  SWITCH_MODE: "SWITCH_MODE",
  SET_GIG_DATA:"SET_GIG_DATA",
  HAS_USER_ORDERED_GIG: "HAS_USER_ORDERED_GIG",
  ADD_REVIEW: "ADD_REVIEW",
}